import Header from "@/components/layout/Header";
import localFont from "next/font/local";

import type { Metadata } from "next";
import { Inter } from "next/font/google"; // 👈 Inter로 변경
import "./globals.css";

// Inter 폰트 정의
const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} bg-gray-100`}>
      <body
        className={`${pretendard.className} antialiased w-full bg-gray-100`} // w-full 유지
      >
        {/* Header 컴포넌트 내부에서 중앙 정렬을 처리 */}
        <Header></Header>

        <main className="w-[1200px] h-screen mt-[60px] mx-auto">
          {children}
        </main>
        {/* <Footer></Footer> */}
      </body>
    </html>
  );
}
